<?php
/**
 * This file is part of project Vmoex.
 *
 * Author: Jake
 * Create: 2018-06-07 23:07:36
 */

namespace Yeskn\WebBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SendMailTestCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this->setName('send-mail');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->getContainer()->get('mailer')
            ->send(
                (new \Swift_Message('Hello, New one', 'this is a test mail', 'text/html', 'utf-8'))
                ->setTo('singviy@qq.com')
                ->setFrom('support@vmoex.com')
            );

        $output->writeln('finished');
    }
}