<?php

namespace Yeskn\BlogBundle\Repository;

/**
 * ActiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiveRepository extends \Doctrine\ORM\EntityRepository
{
}
